#!/bin/bash

xhost +local:docker

docker run -d --rm --privileged \
  -e DISPLAY=unix$DISPLAY \
  -v $HOME:/home/user \
  -v /etc/machine-id:/etc/machine-id \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /dev:/dev \
  -v /run:/run \
  --ipc=host \
  dimaskiddo/ubuntu-armhf:chromium-78.0 \
  chromium-browser \
  --user-agent='Mozilla/5.0 (X11; CrOS armv7l 12607.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.123 Safari/537.36' \
  $1

exit 0
